
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mcp-cni-debugger
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: mcp-cni-debugger
  template:
    metadata:
      labels:
        name: mcp-cni-debugger
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: mcp-cni-debugger
      containers:
      - name: mcp-debugger
        image: <url> 
        imagePullPolicy: Always
        env:
        - name: CONTAINERD_ADDRESS
          value: /run/containerd/containerd.sock  
        volumeMounts:
        - name: run-dir
          mountPath: /var/run/aws-node
        - name: iptables
          mountPath: /var/run/xtables.lock
        - mountPath: /run/containerd/containerd.sock
          name: containerd-sock    
        securityContext:
          privileged: true
      volumes:
      - name: run-dir
        hostPath:
          path: /var/run/aws-node
      - name: iptables
        hostPath:
          path: /run/xtables.lock
      - name: containerd-sock
        hostPath:
          path: /run/containerd/containerd.sock      
