
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-cni-debugger
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-cni-debugger
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-cni-debugger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-cni-debugger
subjects:
- kind: ServiceAccount
  name: mcp-cni-debugger
  namespace: kube-system
